# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rp < Formula
  desc "Repo manager CLI — organize, sync, and bootstrap your Developer workspace"
  homepage "https://github.com/deligoez/rp"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/rp/releases/download/v0.7.0/rp_0.7.0_macOS_x86_64.tar.gz"
      sha256 "d994aa2dc12c7525f50e1814e7f46a7cb1441631200b860d3ddea303573dcff3"

      define_method(:install) do
        bin.install "rp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/rp/releases/download/v0.7.0/rp_0.7.0_macOS_arm64.tar.gz"
      sha256 "c7a6a974aa6c035e5c7804330ada280d8296db1e3622a6f195d6e43122e31099"

      define_method(:install) do
        bin.install "rp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/rp/releases/download/v0.7.0/rp_0.7.0_linux_x86_64.tar.gz"
      sha256 "e9a1de591ae5c32440a32daf26f03fa49968f78fbc188db7ad4b6fa3d8683e41"
      define_method(:install) do
        bin.install "rp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/rp/releases/download/v0.7.0/rp_0.7.0_linux_arm64.tar.gz"
      sha256 "bd19806705c44c144a52e8234e283e8208af9906838259e47426bbec4f5e6687"
      define_method(:install) do
        bin.install "rp"
      end
    end
  end

  test do
    assert_match "rp version", shell_output("#{bin}/rp --version")
  end
end
