# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cr < Formula
  desc "Code review lifecycle manager for AI coding agents"
  homepage "https://github.com/deligoez/cr"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/cr/releases/download/v0.12.0/cr_0.12.0_macOS_x86_64.tar.gz"
      sha256 "ba5811f40ab9555f3da718c0107b03309d819a9036e4ea88304b43aea2d14852"

      define_method(:install) do
        bin.install "cr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/cr/releases/download/v0.12.0/cr_0.12.0_macOS_arm64.tar.gz"
      sha256 "5f11882de03bdab1b5368282c60f38396385fd547c65ff5a0d2cd596d31a0168"

      define_method(:install) do
        bin.install "cr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/cr/releases/download/v0.12.0/cr_0.12.0_linux_x86_64.tar.gz"
      sha256 "6783c92883f748008c8f061c5d46f816b0e0ad414ef41bf5d1a2e314e39df569"
      define_method(:install) do
        bin.install "cr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/cr/releases/download/v0.12.0/cr_0.12.0_linux_arm64.tar.gz"
      sha256 "794b1ebdbad3b5a94e2c0cecbd9c96249ae2afa6f5d49d5d485e7501a040fa09"
      define_method(:install) do
        bin.install "cr"
      end
    end
  end

  test do
    assert_match "cr version", shell_output("#{bin}/cr --version")
  end
end
