# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cr < Formula
  desc "Code review lifecycle manager for AI coding agents"
  homepage "https://github.com/deligoez/cr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/cr/releases/download/v0.1.0/cr_0.1.0_macOS_x86_64.tar.gz"
      sha256 "5640ca6e14f0b33524f47d7b835eecbf3b4789e3970aa4d50e262f107e22cecd"

      define_method(:install) do
        bin.install "cr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/cr/releases/download/v0.1.0/cr_0.1.0_macOS_arm64.tar.gz"
      sha256 "47ef60e9419e8f7153f91644dec86fb93a645dbd5b4effb7bfa011bc8434795d"

      define_method(:install) do
        bin.install "cr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/cr/releases/download/v0.1.0/cr_0.1.0_linux_x86_64.tar.gz"
      sha256 "6ebd2dcffbaed76e61651ba80c2e02f25248314605662202fe6a1a51ed5f5844"
      define_method(:install) do
        bin.install "cr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/cr/releases/download/v0.1.0/cr_0.1.0_linux_arm64.tar.gz"
      sha256 "680f93e31f99297a0ddd77d5b8955b0ac8b2bec50b2a295fe3106455c65ff9f1"
      define_method(:install) do
        bin.install "cr"
      end
    end
  end

  test do
    assert_match "cr version", shell_output("#{bin}/cr --version")
  end
end
