# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cr < Formula
  desc "Code review lifecycle manager for AI coding agents"
  homepage "https://github.com/deligoez/cr"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/cr/releases/download/v0.9.0/cr_0.9.0_macOS_x86_64.tar.gz"
      sha256 "3e0178553ea5e9010570aa48c0c596637c20baf7f7b136a1f3da00eab6ee21ad"

      define_method(:install) do
        bin.install "cr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/cr/releases/download/v0.9.0/cr_0.9.0_macOS_arm64.tar.gz"
      sha256 "c6f5d4ce9862faa69cc157f7c979fa459805ac67e7030c27c88c5c4db7dbb64f"

      define_method(:install) do
        bin.install "cr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/cr/releases/download/v0.9.0/cr_0.9.0_linux_x86_64.tar.gz"
      sha256 "cce4580594ab3bd455c8c9930eae8e45f41800e9ed93fa0ebe3ab4b429d43587"
      define_method(:install) do
        bin.install "cr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/cr/releases/download/v0.9.0/cr_0.9.0_linux_arm64.tar.gz"
      sha256 "4c7a711baee7133a29e9f1f54bf0e79a194481bd8b642756ba402f744435b09e"
      define_method(:install) do
        bin.install "cr"
      end
    end
  end

  test do
    assert_match "cr version", shell_output("#{bin}/cr --version")
  end
end
