# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeligoezHc < Formula
  desc "Hunk-based atomic git commits for AI agents"
  homepage "https://github.com/deligoez/hc"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/hc/releases/download/v0.8.0/hc_0.8.0_macOS_x86_64.tar.gz"
      sha256 "1c000d15c6ae599adc39fb980f422be6c5c7491b4240e1070f3bff256fc3216a"

      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/hc/releases/download/v0.8.0/hc_0.8.0_macOS_arm64.tar.gz"
      sha256 "e598ebd5babc93251147d330f7cb649e2cf580124e48fa818b9425ff57858872"

      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.8.0/hc_0.8.0_linux_x86_64.tar.gz"
      sha256 "1ab3f2eb481a6ae7d3e5fed6100c76d3113c224cce9e23c430e539db9d068d06"
      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.8.0/hc_0.8.0_linux_arm64.tar.gz"
      sha256 "f9cba78709c40eaa59a5fda81a07616d8e64155a1383b0c3e42f97b0ef57b94d"
      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  test do
    assert_match "hc version", shell_output("#{bin}/hc --version")
  end
end
