# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeligoezRp < Formula
  desc "Repo manager CLI — organize, sync, and bootstrap your Developer workspace"
  homepage "https://github.com/deligoez/rp"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/rp/releases/download/v0.8.0/rp_0.8.0_macOS_x86_64.tar.gz"
      sha256 "79b8a94258519d4dc1815ade20b6b33cfc01294fa546421b0ea2a956cdf49a94"

      define_method(:install) do
        bin.install "rp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/rp/releases/download/v0.8.0/rp_0.8.0_macOS_arm64.tar.gz"
      sha256 "4f6e4a3429e788da476490f4000d1b4c7c82055cf29a9f17ada832981de49e23"

      define_method(:install) do
        bin.install "rp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/rp/releases/download/v0.8.0/rp_0.8.0_linux_x86_64.tar.gz"
      sha256 "0a28aaa5ff499940888cf7d89ba1533226ed2218b93d60fe0dde0c2a6861f49a"
      define_method(:install) do
        bin.install "rp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/rp/releases/download/v0.8.0/rp_0.8.0_linux_arm64.tar.gz"
      sha256 "faedd04e81ce349742f990fd2a751bd9d3832742cdeab2c29da3c39c3aad8b4d"
      define_method(:install) do
        bin.install "rp"
      end
    end
  end

  test do
    assert_match "rp version", shell_output("#{bin}/rp --version")
  end
end
