# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeligoezRp < Formula
  desc "Repo manager CLI — organize, sync, and bootstrap your Developer workspace"
  homepage "https://github.com/deligoez/rp"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/rp/releases/download/v0.9.0/rp_0.9.0_macOS_x86_64.tar.gz"
      sha256 "a0c2fda56abc41d6762339261d5f15c42dd22abc60e9c11d249a643325092c17"

      define_method(:install) do
        bin.install "rp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/rp/releases/download/v0.9.0/rp_0.9.0_macOS_arm64.tar.gz"
      sha256 "8dc186a1743bc2a8fc1c7c3b0f4231edd105ed7788f57acbf3e25e6a87e05f3e"

      define_method(:install) do
        bin.install "rp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/rp/releases/download/v0.9.0/rp_0.9.0_linux_x86_64.tar.gz"
      sha256 "971167eaab9e05f3b667d683c4a51f1da8f767fbcdfdf5f218982716d262f09c"
      define_method(:install) do
        bin.install "rp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/rp/releases/download/v0.9.0/rp_0.9.0_linux_arm64.tar.gz"
      sha256 "0aa44bfca2a43548fadba52589ae2a054087e6205eb4d3847b136ea85ec45901"
      define_method(:install) do
        bin.install "rp"
      end
    end
  end

  test do
    assert_match "rp version", shell_output("#{bin}/rp --version")
  end
end
