# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ev < Formula
  desc "Agent-first home inventory"
  homepage "https://github.com/deligoez/ev"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/ev/releases/download/v0.3.0/ev_0.3.0_macOS_x86_64.tar.gz"
      sha256 "cfb55f8cd1469b615247696983bf64c865633d3e8141254b29d9f90bc9c3f4cd"

      define_method(:install) do
        bin.install "ev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/ev/releases/download/v0.3.0/ev_0.3.0_macOS_arm64.tar.gz"
      sha256 "957db6726bed4bfe1d1b7f8158fc1b45bfbcae2ed66a5f9f5f41ccc723c86d17"

      define_method(:install) do
        bin.install "ev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/ev/releases/download/v0.3.0/ev_0.3.0_linux_x86_64.tar.gz"
      sha256 "e98ae4fb9c2312f1e920f1c2b705c401a54721a69f4483686a3be83e68757e43"
      define_method(:install) do
        bin.install "ev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/ev/releases/download/v0.3.0/ev_0.3.0_linux_arm64.tar.gz"
      sha256 "5da6a5cbf9f06e85957d4777865fd51e5d9cd591cc8bacc684543baf62b3c659"
      define_method(:install) do
        bin.install "ev"
      end
    end
  end

  test do
    assert_match "ev #{version}", shell_output("#{bin}/ev --version")
  end
end
