# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ev < Formula
  desc "Agent-first home inventory"
  homepage "https://github.com/deligoez/ev"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/ev/releases/download/v0.9.0/ev_0.9.0_macOS_x86_64.tar.gz"
      sha256 "1715bbda702f1c541dd6c797d3888348faece58e4ca54f9ed9724937484d2606"

      define_method(:install) do
        bin.install "ev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/ev/releases/download/v0.9.0/ev_0.9.0_macOS_arm64.tar.gz"
      sha256 "e1b99d783d33f7531382fbb03f32ce924bb929a2e888f5443bc1cb3e49bcdc25"

      define_method(:install) do
        bin.install "ev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/ev/releases/download/v0.9.0/ev_0.9.0_linux_x86_64.tar.gz"
      sha256 "1d6ec907381f202c9b66bba932bf423fd74e6879d74d5a688584ff718b5464d3"
      define_method(:install) do
        bin.install "ev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/ev/releases/download/v0.9.0/ev_0.9.0_linux_arm64.tar.gz"
      sha256 "d8d4d53615e7fdb7b243b61c81213bfb3aac435a1480b787a97337492bfccff0"
      define_method(:install) do
        bin.install "ev"
      end
    end
  end

  test do
    assert_match "ev #{version}", shell_output("#{bin}/ev --version")
  end
end
