# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hc < Formula
  desc "Hunk-based atomic git commits for AI agents"
  homepage "https://github.com/deligoez/hc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_macOS_x86_64.tar.gz"
      sha256 "74e066b78b63d6e301fd0f9f5009beb994cddd697c5464d7c8999f1b64140c74"

      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_macOS_arm64.tar.gz"
      sha256 "3f4ede40ece436a011a8f43e96ef16c543e47de3bef790ae0f18eabaa6635116"

      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_linux_x86_64.tar.gz"
      sha256 "05a918462f223f45ef89efab5ffd8a966483c69561ef96a523102f7dbd6079b2"
      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_linux_arm64.tar.gz"
      sha256 "c6ea1b9193fb2bbf1c1fa315888f62335e287ca20ba4d243f340b9907bfc50ce"
      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  test do
    assert_match "hc version", shell_output("#{bin}/hc --version")
  end
end
