# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hc < Formula
  desc "Hunk-based atomic git commits for AI agents"
  homepage "https://github.com/deligoez/hc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_macOS_x86_64.tar.gz"
      sha256 "14176225e8272570f02bff32e9d9562d16b83b10a237092936bcaf5ee3d8aaea"

      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_macOS_arm64.tar.gz"
      sha256 "4e0835163f8da3b8867f1c0566153b8cc9f8d3c227fdd6d924a7680beca9b3c7"

      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_linux_x86_64.tar.gz"
      sha256 "c11e979d1b4100065a4dc7505031470d1cff86e75907baadcdc613ee81538a63"
      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_linux_arm64.tar.gz"
      sha256 "57d8d0e0df82ae150360db5f743d1f34d1b7fa8c0c5a2814f2115f573a1adb56"
      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  test do
    assert_match "hc version", shell_output("#{bin}/hc --version")
  end
end
