# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hc < Formula
  desc "Hunk-based atomic git commits for AI agents"
  homepage "https://github.com/deligoez/hc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_macOS_x86_64.tar.gz"
      sha256 "38c1f068dd8cde0815296ec980e74867bd6aef8e9b86adcfa5a29d596d47edc0"

      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_macOS_arm64.tar.gz"
      sha256 "36de3f4faa8fc98774648b3d87254e610731b299f04d1e6296e081b97bc25f9d"

      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_linux_x86_64.tar.gz"
      sha256 "4afde53f48d1d544625c70b66a3e01e8705eb01989b8177a0cdb907d0bd7ad51"
      define_method(:install) do
        bin.install "hc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/hc/releases/download/v0.1.0/hc_0.1.0_linux_arm64.tar.gz"
      sha256 "c184cee2d248d2f746cf60888c034634fbb89f45ad927c85168124acabe04bae"
      define_method(:install) do
        bin.install "hc"
      end
    end
  end

  test do
    assert_match "hc version", shell_output("#{bin}/hc --version")
  end
end
