# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tp < Formula
  desc "Spec-to-task lifecycle manager for AI coding agents"
  homepage "https://github.com/deligoez/tp"
  version "0.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deligoez/tp/releases/download/v0.23.0/tp_0.23.0_macOS_x86_64.tar.gz"
      sha256 "e6bfbf5ac9d3e591229538841d558adf74a6af427e050fede78d7b61712fa6b7"

      define_method(:install) do
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deligoez/tp/releases/download/v0.23.0/tp_0.23.0_macOS_arm64.tar.gz"
      sha256 "a7243c22a4a2785bb51fa4d674f65c44d948fc9ae1d76a37980993fcee95125f"

      define_method(:install) do
        bin.install "tp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/tp/releases/download/v0.23.0/tp_0.23.0_linux_x86_64.tar.gz"
      sha256 "717b013e0b49f829aed8785882eba9aa981b777745bef6b354ca090f83ba977b"
      define_method(:install) do
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deligoez/tp/releases/download/v0.23.0/tp_0.23.0_linux_arm64.tar.gz"
      sha256 "46b4f2f968203c956b08f914d89a335a855c0cafb954bf3e3d4d3af2f9f06a15"
      define_method(:install) do
        bin.install "tp"
      end
    end
  end

  test do
    assert_match "tp version", shell_output("#{bin}/tp --version")
  end
end
